### ISSUE TITLE
Kings break when taking 4 pieces and end up on the same square.

### ISSUE THREAD

**Issue by kojima100** [kojima100/Draughts_AI#8]
The position [FEN "B:W32,29,28,27,26,25,22,18,17:BK30,10,9,8,7,5,4,3,2,1"] shows the error.
![kingerror](https://cloud.githubusercontent.com/assets/1832667/11289858/c36bafe6-8f28-11e5-95c6-bccf1d36fc45.PNG)

**Comment by maxaction** [comment]
fixed in 3eab3e8
