### ISSUE TITLE
King Takes Break on 5 chain

### ISSUE THREAD

**Issue by kojima100** [kojima100/Draughts_AI#9]
The position [FEN "W:W32,31,30,28,24,21,20,13,K1:B18,16,15,8,7,6,4,2"] shows the error.

![kingerror2](https://cloud.githubusercontent.com/assets/1832667/11320095/abce2eea-9086-11e5-9742-49407bd22495.PNG)

**Comment by maxaction** [comment]
fixed in  637a56a
